baseURL = 'https://sedna-works.github.io'
languageCode = 'zh-cn'
title = "Sedna Works"
theme = 'hugo-mini'

[params]

  [params.theme_config]
    appearance        = "auto"
    back_home_text    = ".."
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = false

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = true
    lineNumbersInTable = false
    noClasses          = true
    noHl               = false
    style              = 'autumn'
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 6
    ordered    = false
